# Generated by Django 4.2.7 on 2026-02-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet_tipi', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Avrupa Paleti (120x80x180 cm)'), (2, 'ISO Standart (120x100x200 cm)'), (3, 'Asya Paleti (110x110x190 cm)'), (4, 'ABD Paleti (121.9x101.6x200 cm)')], null=True, verbose_name='Palet Tipi')),
                ('container_length', models.FloatField(blank=True, null=True, verbose_name='Container Uzunluk (cm)')),
                ('container_width', models.FloatField(blank=True, null=True, verbose_name='Container Genişlik (cm)')),
                ('container_height', models.FloatField(blank=True, null=True, verbose_name='Container Yükseklik (cm)')),
                ('container_weight', models.FloatField(blank=True, null=True, verbose_name='Container Max Ağırlık (kg)')),
                ('baslangic_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('toplam_palet', models.PositiveIntegerField(default=0, verbose_name='Toplam Palet Sayısı')),
                ('single_palet', models.PositiveIntegerField(default=0, verbose_name='Single Palet Sayısı')),
                ('mix_palet', models.PositiveIntegerField(default=0, verbose_name='Mix Palet Sayısı')),
                ('pie_chart', models.ImageField(blank=True, null=True, upload_to='optimizasyon_grafikler/', verbose_name='Pasta Grafiği')),
                ('bar_chart', models.ImageField(blank=True, null=True, upload_to='optimizasyon_grafikler/', verbose_name='Çubuk Grafiği')),
                ('islem_durumu', models.TextField(default='{"current_step": 0, "total_steps": 5, "messages": []}', verbose_name='İşlem Durumu')),
                ('yerlesmemis_urunler', models.JSONField(default=list, verbose_name='Yerleştirilemeyen Ürünler')),
                ('algoritma', models.CharField(default='greedy', max_length=20, verbose_name='Algoritma')),
            ],
            options={
                'verbose_name': 'Optimizasyon',
                'verbose_name_plural': 'Optimizasyonlar',
                'ordering': ['-baslangic_zamani'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=20, verbose_name='Ürün Kodu')),
                ('urun_adi', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('boy', models.FloatField(verbose_name='Boy (cm)')),
                ('en', models.FloatField(verbose_name='En (cm)')),
                ('yukseklik', models.FloatField(verbose_name='Yükseklik (cm)')),
                ('agirlik', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('mukavemet', models.FloatField(verbose_name='Mukavemet (kg)')),
                ('donus_serbest', models.BooleanField(default=False, verbose_name='Dönüş Serbest')),
                ('istiflenebilir', models.BooleanField(default=True, verbose_name='İstiflenebilir')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet_id', models.PositiveIntegerField(verbose_name='Palet ID')),
                ('palet_tipi', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Avrupa Paleti (120x80x180 cm)'), (2, 'ISO Standart (120x100x200 cm)'), (3, 'Asya Paleti (110x110x190 cm)'), (4, 'ABD Paleti (121.9x101.6x200 cm)')], null=True, verbose_name='Palet Tipi')),
                ('palet_turu', models.CharField(choices=[('single', 'Single Palet'), ('mix', 'Mix Palet')], default='mix', max_length=10, verbose_name='Palet Türü')),
                ('custom_en', models.FloatField(blank=True, null=True, verbose_name='Özel En (cm)')),
                ('custom_boy', models.FloatField(blank=True, null=True, verbose_name='Özel Boy (cm)')),
                ('custom_max_yukseklik', models.FloatField(blank=True, null=True, verbose_name='Özel Max Yükseklik (cm)')),
                ('custom_max_agirlik', models.FloatField(blank=True, null=True, verbose_name='Özel Max Ağırlık (kg)')),
                ('toplam_agirlik', models.FloatField(default=0.0, verbose_name='Toplam Ağırlık (kg)')),
                ('kullanilan_hacim', models.FloatField(default=0.0, verbose_name='Kullanılan Hacim (cm³)')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='palet_gorseller/', verbose_name='Palet Görseli')),
                ('urun_konumlari', models.JSONField(default=dict, verbose_name='Ürün Konumları')),
                ('urun_boyutlari', models.JSONField(default=dict, verbose_name='Ürün Boyutları')),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletler', to='palet_app.optimization', verbose_name='Optimizasyon')),
            ],
            options={
                'verbose_name': 'Palet',
                'verbose_name_plural': 'Paletler',
                'ordering': ['palet_id'],
                'unique_together': {('optimization', 'palet_id')},
            },
        ),
    ]
